"""
Order manager for the Hybrid Intelligence Commodities Trader.

Validates trades against risk constraints before opening or closing positions.
Acts as the gatekeeper between strategy signals and the portfolio.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

import config
from src.execution.portfolio import Portfolio, Position
from src.execution.risk_manager import RiskManager

logger = logging.getLogger(__name__)


@dataclass
class TradeSignal:
    """A proposed trade generated by a strategy."""

    symbol: str
    position_type: str       # "long" or "short"
    quantity: float
    entry_price: float
    stop_loss: float
    take_profit: float | None = None
    rationale: str = ""

    @property
    def notional_value(self) -> float:
        return abs(self.quantity) * self.entry_price


class OrderManager:
    """
    Validates and executes trade signals against risk constraints.

    Parameters
    ----------
    portfolio:
        The live :class:`~src.execution.portfolio.Portfolio`.
    risk_manager:
        The :class:`~src.execution.risk_manager.RiskManager` for constraint checks.
    """

    def __init__(self, portfolio: Portfolio, risk_manager: RiskManager) -> None:
        self._portfolio = portfolio
        self._risk_manager = risk_manager

    def submit_order(
        self,
        signal: TradeSignal,
        current_prices: dict[str, float] | None = None,
    ) -> bool:
        """
        Validate a trade signal and open the position if it passes all checks.

        Checks (in order):
        1. Capital allocation limit (30%).
        2. Kill switch drawdown check.
        3. Position already open for the symbol.

        Parameters
        ----------
        signal:
            The proposed trade.
        current_prices:
            Current market prices used for equity calculations.

        Returns
        -------
        *True* if the order was accepted and opened, *False* otherwise.
        """
        prices = current_prices or {}

        # Check kill switch before allowing new trades
        if self._risk_manager.check_kill_switch(prices):
            logger.warning("Order rejected: kill switch triggered.")
            return False

        # Check capital allocation
        if not self._risk_manager.check_allocation(signal.notional_value, prices):
            logger.warning(
                "Order rejected for %s: would exceed %.0f%% capital allocation limit.",
                signal.symbol,
                config.MAX_CAPITAL_ALLOCATION * 100,
            )
            return False

        # Check for duplicate position
        if signal.symbol in self._portfolio.positions:
            logger.warning(
                "Order rejected for %s: position already open.", signal.symbol
            )
            return False

        position = Position(
            symbol=signal.symbol,
            quantity=signal.quantity,
            entry_price=signal.entry_price,
            position_type=signal.position_type,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
        )
        try:
            self._portfolio.open_position(position)
            logger.info(
                "Order ACCEPTED: %s %s qty=%.4f @ %.4f (%s)",
                signal.position_type.upper(),
                signal.symbol,
                signal.quantity,
                signal.entry_price,
                signal.rationale,
            )
            return True
        except ValueError as exc:
            logger.warning("Order rejected: %s", exc)
            return False

    def close_order(
        self, symbol: str, exit_price: float
    ) -> float | None:
        """
        Close an open position.

        Returns
        -------
        Realised PnL, or *None* if no position was open.
        """
        if symbol not in self._portfolio.positions:
            logger.warning("Close order ignored: no open position for %s.", symbol)
            return None
        return self._portfolio.close_position(symbol, exit_price)
